from prompts.idea_prompts import (
    ASSUMPTION_BREAKING_PROMPT,
    PROBLEM_REFRAMING_PROMPT,
    STORY_ARC_PROMPT,
    NECESSITY_CHECK_PROMPT,
    DERIVATION_TRACE_PROMPT,
    METHOD_LOCK_PROMPT,
    PROPOSAL_PROMPT,
    GAP_ANALYSIS_PROMPT,
)
